spring.application.name=buildMart

spring.mongodb.uri=mongodb://mongo:AoEIGgbPWUVFusOVfQHfekdWCeoVvLyb@mongodb.railway.internal:27017
spring.data.mongodb.database=buildmart

spring.web.resources.static-locations=classpath:/,classpath:/images/,classpath:/pages/,classpath:/scripts/,classpath:/styles/logging.level.org.springframework.web=DEBUG