spring.application.name=buildMart

spring.mongodb.uri=mongodb://localhost:27017/buildmart

spring.web.resources.static-locations=classpath:/,classpath:/images/,classpath:/pages/,classpath:/scripts/,classpath:/styles/logging.level.org.springframework.web=DEBUG