spring.application.name=buildMart

spring.data.mongodb.database=buildmart

spring.web.resources.static-locations=classpath:/,classpath:/images/,classpath:/pages/,classpath:/scripts/,classpath:/styles/