spring.application.name=buildMart

spring.mongodb.uri=mongodb://localhost:27017/buildmart

spring.web.resources.static-locations=file:D:/Java/buildMart/,file:./styles/,file:./scripts/,file:./pages/,file:./scripts_test/,file:./styles_test/
logging.level.org.springframework.web=DEBUG